2023-02-27 18:05:28,832 ERROR frappe Could not take error snapshot: characters_written
Site: mysite.localhost
Form Dict: {'language': 'es', 'cmd': 'frappe.translate.get_messages'}
Traceback (most recent call last):
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=es&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7f8635327430%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/translate.py", line 1239, in get_messages
    translated_dict = translator.post_api(
  File "/workspace/development/frappe-bench/apps/frappe/frappe/frappeclient.py", line 341, in post_api
    res = self.session.post(
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=es&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7f8635327430%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/error.py", line 47, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/error.py", line 140, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
